# -*- coding: utf-8 -*-
"""kadyrova_9_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4nwxHllslpmttUW-knYGiti9EZGUfR0
"""

import pandas as pd
import matplotlib.pyplot as plt


def load_dataframe(filename):
    """Загрузка данных из CSV-файла"""
    return pd.read_csv(filename)


def line_chart_2023(df):
    """Линейный график прочитанных книг за 2023 год"""
    plt.plot(
        df["Месяц"],
        df["Книги"],
        marker='o',
        color='red',
        label="Прочитано книг"
    )
    plt.title("Прочитанные книги 2023")
    plt.xlabel("Месяцы")
    plt.ylabel("Количество книг")
    plt.grid(True)
    plt.legend()


def bar_chart_2024(df):
    """Столбчатая диаграмма прочитанных страниц за 2024 год"""
    plt.bar(
        df["Месяц"],
        df["Страницы"],
        color='green',
        label="Прочитано страниц"
    )
    plt.title("Прочитанные страницы 2024")
    plt.xlabel("Месяцы")
    plt.ylabel("Количество страниц")
    plt.grid(True)
    plt.legend()


def main():
    df = load_dataframe("books.csv")
    print("DataFrame columns:", df.columns.tolist())

    plt.figure(figsize=(12, 6))

    plt.subplot(1, 2, 1)
    line_chart_2023(df)

    plt.subplot(1, 2, 2)
    bar_chart_2024(df)

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()